### ISSUE TITLE
Reuse event loop instead of creating a new one?

### ISSUE THREAD

**Issue by patrick-jones** [phlax/aio.testing#3]
I am using aio.testing to test a service that uses [aiopg](https://github.com/aio-libs/aiopg). It would be nice to set up a single connection pool and then run many tests using the same pool. However, this is not possible because aio.testing creates a new event loop for each test, so calls to aiopg (which live on the event loop in place when the connection pool was created) never return.

Could the test decorators be changed to (optionally) reuse the existing event loop rather than creating temporary loops?

**Comment by phlax** [comment]
yep i think that's probably a good idea.

can you submit a pull request with the necessary changes - i not ill take a look at it later

**Comment by patrick-jones** [comment]
I can do a pull request in the next few days.
